spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.jpa.open-in-view=false
logging.level.org.springframework.security=INFO
app.frontend.url=https://freemoment.de
app.cors.allowed-origins=https://freemoment.de,https://www.freemoment.de
