spring.application.name=server
# Datenbank im Speicher (flüchtig)
#Für Prod: setze spring.datasource.url=jdbc:postgresql://... etc. und sichere das JWT-Secret per ENV.
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# H2-Webkonsole aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging helpful for debugging
logging.level.org.springframework.security=DEBUG

