spring.application.name=server
# Datenbank im Speicher (flüchtig)
#Für Prod: setze spring.datasource.url=jdbc:postgresql://... etc. und sichere das JWT-Secret per ENV.
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# H2-Webkonsole aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Logging helpful for debugging
logging.level.org.springframework.security=DEBUG
#E-Mail
spring.mail.host=smtp.strato.de
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.strato.de
#Frontend-URL für E-Mail-Links
app.frontend.url=http://localhost:8080


