spring.application.name=server
# Datenbank im Speicher (flüchtig)
#Für Prod: setze spring.datasource.url=jdbc:postgresql://... etc. und sichere das JWT-Secret per ENV.
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# H2-Webkonsole aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging helpful for debugging
logging.level.org.springframework.security=DEBUG

#E-Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deine.email@gmail.com
spring.mail.password=deinAppPasswort
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


