--
-- PostgreSQL database dump
--

\restrict NciIwfjVhAqiwYzXEB2rTsi6Mb8f5p5rtnSdZrIzRSNMjRZmFXEiGezRIvJap8J

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: freemoment_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO freemoment_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.app_user (
    is_banned boolean,
    profile_image_offset_x double precision,
    profile_image_offset_y double precision,
    profile_image_scale double precision,
    banned_until timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    profile_image_id bigint,
    about_me character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.app_user OWNER TO freemoment_user;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user_roles; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.app_user_roles (
    user_id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT app_user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_MODERATOR'::character varying, 'ROLE_ADMIN'::character varying, 'ROLE_ROOT'::character varying])::text[])))
);


ALTER TABLE public.app_user_roles OWNER TO freemoment_user;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO freemoment_user;

--
-- Name: images; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.images (
    image_order integer,
    creation_date_time timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    location_id bigint,
    size bigint NOT NULL,
    uploaded_by_user_id bigint NOT NULL,
    content_type character varying(255),
    filename character varying(255) NOT NULL
);


ALTER TABLE public.images OWNER TO freemoment_user;

--
-- Name: images_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.location (
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    thumbnail_offset_x double precision,
    thumbnail_offset_y double precision,
    thumbnail_scale double precision,
    created_user_id bigint NOT NULL,
    creation_date_time timestamp(6) without time zone NOT NULL,
    end_date_time timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    start_date_time timestamp(6) without time zone NOT NULL,
    thumbnail_image_id bigint,
    address character varying(255),
    description character varying(255),
    title character varying(255)
);


ALTER TABLE public.location OWNER TO freemoment_user;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location_join; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.location_join (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.location_join OWNER TO freemoment_user;

--
-- Name: location_join_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.location_join ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_join_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location_like; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.location_like (
    id bigint NOT NULL,
    liked_at timestamp(6) without time zone NOT NULL,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.location_like OWNER TO freemoment_user;

--
-- Name: location_like_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.location_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.password_reset_tokens (
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_mail_sent_at timestamp(6) without time zone,
    used_at timestamp(6) without time zone,
    token character varying(64) NOT NULL,
    email character varying(255) NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO freemoment_user;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pending_user; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.pending_user (
    expires_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_mail_sent_at timestamp(6) without time zone,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password_hash character varying(255),
    username character varying(255) NOT NULL,
    verify_token character varying(255)
);


ALTER TABLE public.pending_user OWNER TO freemoment_user;

--
-- Name: pending_user_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

CREATE SEQUENCE public.pending_user_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pending_user_seq OWNER TO freemoment_user;

--
-- Name: place; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.place (
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    created_at timestamp(6) without time zone,
    creator_user_id bigint,
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.place OWNER TO freemoment_user;

--
-- Name: place_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_setting; Type: TABLE; Schema: public; Owner: freemoment_user
--

CREATE TABLE public.user_setting (
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    app_design character varying(255),
    language character varying(255),
    CONSTRAINT user_setting_app_design_check CHECK (((app_design)::text = ANY ((ARRAY['SYSTEM'::character varying, 'LIGHTBLACK'::character varying, 'LIGHTROSE'::character varying, 'LIGHTWINE'::character varying, 'DARKWHITE'::character varying, 'DARKPINK'::character varying, 'DARKGOLD'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT user_setting_language_check CHECK (((language)::text = ANY ((ARRAY['SYS'::character varying, 'EN'::character varying, 'DE'::character varying])::text[])))
);


ALTER TABLE public.user_setting OWNER TO freemoment_user;

--
-- Name: user_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: freemoment_user
--

ALTER TABLE public.user_setting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: location_join location_join_location_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_join
    ADD CONSTRAINT location_join_location_id_user_id_key UNIQUE (location_id, user_id);


--
-- Name: location_join location_join_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_join
    ADD CONSTRAINT location_join_pkey PRIMARY KEY (id);


--
-- Name: location_like location_like_location_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_like
    ADD CONSTRAINT location_like_location_id_user_id_key UNIQUE (location_id, user_id);


--
-- Name: location_like location_like_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_like
    ADD CONSTRAINT location_like_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_email_key; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_email_key UNIQUE (email);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);


--
-- Name: pending_user pending_user_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.pending_user
    ADD CONSTRAINT pending_user_pkey PRIMARY KEY (id);


--
-- Name: pending_user pending_user_username_key; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.pending_user
    ADD CONSTRAINT pending_user_username_key UNIQUE (username);


--
-- Name: place place_name_key; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT place_name_key UNIQUE (name);


--
-- Name: place place_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT place_pkey PRIMARY KEY (id);


--
-- Name: user_setting user_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.user_setting
    ADD CONSTRAINT user_setting_pkey PRIMARY KEY (id);


--
-- Name: user_setting user_setting_user_id_key; Type: CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.user_setting
    ADD CONSTRAINT user_setting_user_id_key UNIQUE (user_id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: freemoment_user
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_prt_email; Type: INDEX; Schema: public; Owner: freemoment_user
--

CREATE INDEX idx_prt_email ON public.password_reset_tokens USING btree (email);


--
-- Name: images fk1skc6fgbqx2cwcux5jv2b8dw5; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT fk1skc6fgbqx2cwcux5jv2b8dw5 FOREIGN KEY (location_id) REFERENCES public.location(id);


--
-- Name: location_like fk26ymgpnbgsljoawi488j0b829; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_like
    ADD CONSTRAINT fk26ymgpnbgsljoawi488j0b829 FOREIGN KEY (location_id) REFERENCES public.location(id);


--
-- Name: location fk2ptctu7ypd09srdqak03amq8d; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT fk2ptctu7ypd09srdqak03amq8d FOREIGN KEY (thumbnail_image_id) REFERENCES public.images(id);


--
-- Name: app_user_roles fk3lwiahkol5aetc57pto5olacf; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.app_user_roles
    ADD CONSTRAINT fk3lwiahkol5aetc57pto5olacf FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: location fk5jex6onhe0h13e0aybo6vo8hn; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT fk5jex6onhe0h13e0aybo6vo8hn FOREIGN KEY (created_user_id) REFERENCES public.app_user(id);


--
-- Name: images fk9b981cubt6el7efogl1na3lnv; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT fk9b981cubt6el7efogl1na3lnv FOREIGN KEY (uploaded_by_user_id) REFERENCES public.app_user(id);


--
-- Name: place fka068t3vvs41uqwc34vl0aj6l7; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT fka068t3vvs41uqwc34vl0aj6l7 FOREIGN KEY (creator_user_id) REFERENCES public.app_user(id);


--
-- Name: user_setting fkh3b12dx8r1mp8k5us5omun8l7; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.user_setting
    ADD CONSTRAINT fkh3b12dx8r1mp8k5us5omun8l7 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: location_like fkjalytiamtb1d85eike495uriy; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_like
    ADD CONSTRAINT fkjalytiamtb1d85eike495uriy FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: app_user fkm332a9e41v0bmgops11d0l1it; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fkm332a9e41v0bmgops11d0l1it FOREIGN KEY (profile_image_id) REFERENCES public.images(id);


--
-- Name: location_join fkmag357msx0px6t93dc28clhjq; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_join
    ADD CONSTRAINT fkmag357msx0px6t93dc28clhjq FOREIGN KEY (location_id) REFERENCES public.location(id);


--
-- Name: location_join fkq5g3p5u078bupiqar9oo8bj2n; Type: FK CONSTRAINT; Schema: public; Owner: freemoment_user
--

ALTER TABLE ONLY public.location_join
    ADD CONSTRAINT fkq5g3p5u078bupiqar9oo8bj2n FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- PostgreSQL database dump complete
--

\unrestrict NciIwfjVhAqiwYzXEB2rTsi6Mb8f5p5rtnSdZrIzRSNMjRZmFXEiGezRIvJap8J

