name: Deploy Spring Boot to Strato

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  #pull_request:
  #  branches: [ main ]

env:
  HOST: ${{ secrets.STRATO_HOST }}
  PORT: ${{ secrets.STRATO_PORT }}
  USERNAME: ${{ secrets.STRATO_USER }}
  SSH_KEY: ${{ secrets.STRATO_SSH_KEY }}
  APP_PATH: ${{ vars.APP_PATH }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  #only for aws
  AWS_REGION: eu-central-1          # z. B. Frankfurt
  ECR_REPOSITORY: freemomentrepo    # Name deines ECR-Repos
  ECS_CLUSTER: freemomentCluster
  ECS_SERVICE: freemomentService

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: dev
          JWT_SECRET: test_secret_1234567890123456789012345678901234567890
          MAIL_USERNAME: test@example.com
          MAIL_PASSWORD: test-password
        
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          source: target/*.jar
          #target: ${{ env.APP_PATH }}/deploy
          target: /opt/freemoment/deploy
          
          
      - name: Restart application on Strato
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            set -e
            APP_PATH="/opt/freemoment"
            SERVICE_NAME="freemoment"
      
            JAR=$(ls "$APP_PATH/deploy/target/"*.jar | head -n 1)
            cp "$JAR" "$APP_PATH/app.jar"
      
            sudo systemctl restart "$SERVICE_NAME"
            sudo systemctl status "$SERVICE_NAME" --no-pager
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
 #       with:
 #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: ${{ env.AWS_REGION }}
#
#      - name: Log in to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#
#      - name: Build, tag, and push image to Amazon ECR
#        run: |
#          IMAGE_TAG=${{ github.sha }}
#          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
#          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
#          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
#        env:
#          AWS_REGION: ${{ env.AWS_REGION }}

  #    - name: Render ECS task definition
  #      run: |
  #        IMAGE_TAG=${{ github.sha }}
  #        sed "s|<IMAGE>|${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG|; \
 #              s|\${ECS_EXECUTION_ROLE_ARN}|${{ secrets.ECS_EXECUTION_ROLE_ARN }}|" \
 #              ecs-task-def-template.json > ecs-task-def.json

 #     - name: Deploy to Amazon ECS
 #       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  #      with:
   #       task-definition: ecs-task-def.json
   #       service: ${{ env.ECS_SERVICE }}
   #       cluster: ${{ env.ECS_CLUSTER }}
    #      wait-for-service-stability: true
